### ISSUE TITLE
How to get emit event in vuex?

### ISSUE THREAD

**Issue by XGHeaven** [cklmercer/vue-events#13]
I want to emit an event to event bus in vuex mutations. How to do?

**Comment by cklmercer** [comment]
This isn't supported at the moment. You could extend this plugin so that it exports both the plugin function and the event bus. Then you'd just need to import the event bus.

**Comment by XGHeaven** [comment]
If you want to put in feature to plan in the future？

On Oct 3, 2017 00:03, "Cody Mercer" <notifications@github.com> wrote:

Closed #13 <https://github.com/cklmercer/vue-events/issues/13>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cklmercer/vue-events/issues/13#event-1274332525>, or mute
the thread

**Comment by cklmercer** [comment]
I'll look into adding this feature, but it could be a little while before I'm able to get to it. In the mean time, I'm 100% open to reviewing and merge PRs! Thanks!
