### ISSUE TITLE
Can v-on be modified to use global events bus

### ISSUE THREAD

**Issue by neeravp** [cklmercer/vue-events#3]
Vue supports inline declaration of events in the html as below:  

 `<div class="parent">  
            <child-component @custom-event="customEventHandler">  
        </div>`

The `customEventHandler` being a method in the parent component. But this works only if the event is emitted on the current vue instance. If we use global event bus like vue-events then we can not have such declaration.  
My question is can the v-on or shorthand '@' be modified to catch the events from the global event bus and have the luxury of using such declarative syntax?

**Comment by cklmercer** [comment]
Off the top of my head, I'd have to guess that this would be pretty tricky. I think you'd probably have to make some kind of commitment to one or the other. I'll take a look into this later this year. Sadly, right now I've got a bit of a to-do list that's built up on me. 

Until I'm able to get to it, I'd be happy to look at PRs which introduce this feature via some sort of configuration option.

**Comment by cklmercer** [comment]
modifying built-in directives is outside of the scope of this plugin.
